### ISSUE TITLE
求助！client_ros的检测结果一直是一样的。。

### ISSUE THREAD

**Issue by Rt1z** [guojianyang/cv-detect-robot#3]
![Screenshot from 2021-09-29 13-32-11](https://user-images.githubusercontent.com/37474567/135209244-264883fb-189d-4972-8402-47d2e0893028.png)
"yolov5-ros/nvdsinfer_custom_impl_yolo"里面的"internal_memory.txt"的内容也一直是一样的。。

**Comment by guojianyang** [comment]
内存文件的操作权限问题

**Comment by teacher1314** [comment]
我感觉是因为就算没有检测到物体，他还是会发送文件中的数据，因为没有数据来更新它
